version: '3.8'

services:
  cam-gateway:
    build: .
    container_name: cam-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"  # Web interface and API
      - "554:554"    # RTSP port
      - "8001-8010:8001-8010"  # ONVIF ports for streams
    volumes:
      - ./data:/app/data  # Persistent data storage
    environment:
      - DATABASE_URL=/app/data/streams.db
      - ONVIF_PORT=8000
      - RTSP_PORT=554
      - LOG_LEVEL=INFO
    networks:
      - cam-network

networks:
  cam-network:
    driver: bridge 